### ISSUE TITLE
Fatal crash: Fatal Python error: Cannot recover from stack overflow

### ISSUE THREAD

**Issue by ohanaali** [mandiant/flare-floss#633]
when running on file: md5:**84c06826f5b4e59c41a793b94b5593eb**

```
Thread 0x00007fe43f8b0700 (most recent call first):
  File "/usr/local/lib/python3.8/dist-packages/halo/halo.py", line 422 in render
  File "/opt/python-3.7.3/lib/python3.7/threading.py", line 870 in run
  File "/opt/python-3.7.3/lib/python3.7/threading.py", line 932 in _bootstrap_inner
  File "/opt/python-3.7.3/lib/python3.7/threading.py", line 890 in _bootstrap
....
```

 appreciate the help

**Comment by mr-tz** [comment]
Good find. Looks like an issue in the binary analysis part (vivisect) that has been fixed in their current master.
With that analysis is still slow, but at least no crash. We'll have to wait for a new vivisect release (which is already in preparation) and then update our dependency.

**Comment by ohanaali** [comment]
awesome thank you for the fast reply

**Comment by Vulcanraven91** [comment]
Any new updates regarding the fix? It still happens on the newest release. 
Too bad that you can't just skip the faulthy segment.


```
## Log

- **DEBUG: floss** - Using default embedded signatures.
- **DEBUG: floss** - To provide your own signatures, use the form `floss.exe --signature ./path/to/signatures/ C:/Users/GoofyUser/AppData/Local/Temp/_MEI90682/sigs`
- **INFO: floss** - extracting static strings...
- **DEBUG: viv_utils.flirt** - parsing .sig: C:/Users/GoofyUser/AppData/Local/Temp/_MEI90682/sigs/1_flare_msvc_rtf_32_64.sig: 0.43s
- **DEBUG: viv_utils.flirt** - sig count: 210632
- **DEBUG: viv_utils.flirt** - compiling sigs: 1.01s
- **DEBUG: viv_utils.flirt** - parsing .sig: C:/Users/GoofyUser/AppData/Local/Temp/_MEI90682/sigs/2_flare_msvc_atlmfc_32_64.sig: 0.71s
- **DEBUG: viv_utils.flirt** - sig count: 381783
- **DEBUG: viv_utils.flirt** - compiling sigs: 1.81s
- **DEBUG: viv_utils.flirt** - parsing .sig: C:/Users/GoofyUser/AppData/Local/Temp/_MEI90682/sigs/3_flare_common_libs.sig: 0.25s
- **DEBUG: viv_utils.flirt** - sig count: 119337
- **DEBUG: viv_utils.flirt** - compiling sigs: 0.56s

## Error

**Fatal Python error: Cannot recover from stack overflow.**

Python runtime state: initialized

Thread 0x00001508 (most recent call first):
  File "halo\halo.py", line 422 in render
  File "threading.py", line 870 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Current thread 0x000001e4 (most recent call first):
File "envi\archs\i386\disasm.py", line 908 in _dis_calc_tsize
  File "envi\archs\i386\disasm.py", line 1027 in disasm
  File "envi\archs\i386\__init__.py", line 36 in archParseOpcode
  File "vivisect\__init__.py", line 1165 in parseOpcode
  File "envi\codeflow.py", line 162 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "envi\codeflow.py", line 243 in addCodeFlow
  File "envi\codeflow.py", line 288 in addEntryPoint
  File "vivisect\__init__.py", line 1528 in makeFunction
  File "vivisect\impemu\monitor.py", line 209 in apicall
  File "vivisect\impemu\emulator.py", line 275 in checkCall
  File "vivisect\impemu\emulator.py", line 500 in runFunction
  File "vivisect\analysis\i386\calling.py", line 137 in analyzeFunction
  File "vivisect\__init__.py", line 821 in analyzeFunction
```

**Comment by mr-tz** [comment]
So far the update is only in master. I can cut a new release here shortly with the updates.

**Comment by mr-tz** [comment]
This should be closed via the new release https://github.com/mandiant/flare-floss/releases/tag/v2.3.0. Otherwise, please reopen this.
